name: anewmeat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  googleapis: ^12.0.0
  http: ^1.1.0
  image_picker: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  location: ^5.0.3
  map_location_picker: ^1.2.8+3
  razorpay_flutter: ^1.3.6
  shared_preferences: ^2.2.2
  skeletonizer: ^0.8.0
  sms_autofill: ^2.3.0

flutter_native_splash:
  image: assets/icons/appicon.png
  color: "#ffffff"
#"#CE3541"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        
  assets:
   - assets/icons/
   - assets/images/
