name: anewmeat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  sms_autofill: ^2.3.0
  water_drop_nav_bar: ^2.2.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  assets:
   - assets/icons/
   - assets/images/
