// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqMrZVoKmW4P8OJDJaLOjE_F3wdjJzKo',
    appId: '1:884283395686:web:977eea3cc69fa6e3aca7a7',
    messagingSenderId: '884283395686',
    projectId: 'anewmeat-73e27',
    authDomain: 'anewmeat-73e27.firebaseapp.com',
    storageBucket: 'anewmeat-73e27.appspot.com',
    measurementId: 'G-VCFZ4K2QJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbsAmiRlRqPr2r7ys5IxFvc99eE1fIC0',
    appId: '1:884283395686:android:44445035f756a543aca7a7',
    messagingSenderId: '884283395686',
    projectId: 'anewmeat-73e27',
    storageBucket: 'anewmeat-73e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPRVl9BXQhNkk9yKNCOnWcYQlZOLCKek',
    appId: '1:884283395686:ios:e9c7e35a97bcfea8aca7a7',
    messagingSenderId: '884283395686',
    projectId: 'anewmeat-73e27',
    storageBucket: 'anewmeat-73e27.appspot.com',
    iosBundleId: 'com.example.anewmeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPRVl9BXQhNkk9yKNCOnWcYQlZOLCKek',
    appId: '1:884283395686:ios:f396fc96713084d8aca7a7',
    messagingSenderId: '884283395686',
    projectId: 'anewmeat-73e27',
    storageBucket: 'anewmeat-73e27.appspot.com',
    iosBundleId: 'com.example.anewmeat.RunnerTests',
  );
}
